name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Backend install
        working-directory: vitashift-backend
        run: npm ci
      - name: Backend typecheck
        working-directory: vitashift-backend
        run: npm run typecheck
      - name: Backend build
        working-directory: vitashift-backend
        run: npm run build
      - name: Backend tests
        working-directory: vitashift-backend
        run: npm test